// WARNING: This file is regenerated by the `cargo func new` command.

mod warpgrapher_handler;

// Export the Azure Functions here.
azure_functions::export! {
    warpgrapher_handler::handler,
}
